name: 'Walk'

on:
  #push:
  schedule:
    # UTC (国内 UTC+8)
     - cron: '03 3 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    #runs-on: macos-latest
    runs-on: ubuntu-latest

    steps:
        - name: 'Checkout codes'
          uses: actions/checkout@v2
          

#         - name: 'Install requirements'
#           run: |
#             pip3 install -r ./requirements.txt
            
        - name: 'Walk'
          env:
            USER: ${{ secrets.USER }}
            PASSWORD: ${{ secrets.PASSWORD }}
            BARK_KEY: ${{ secrets.BARK_KEY }}
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
            TG_USER_ID: ${{ secrets.TG_USER_ID }}

          run: |
            python3 ./main.py
